version: '3'
services:
  api:
    build: ./api
    env_file:
      - env-api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/housekeeping
    ports:
      - "3030:3000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  frontend:
    build: ./frontend
    command: ruby housekeeping.rb -p 80 -o 0.0.0.0
    volumes:
      - ./frontend:/housekeeping
    ports:
      - "8080:80"
    depends_on:
      - api
